print("Ingresa tu nombre")
name = input()
print("Que estas estudiando?")
job_name = input()
print("Ingresa un adjetivo")
first_adjetive = input()
print("Ingresa otro adjetivo")
second_adjetive = input()
print("Ingresa una comida")
first_food = input()
print("Ingresa otra comida")
second_food = input()
print("Ingresa sentimiento")
feeling = input()

print(name + " started their first Generation course today. They are training as a "+ job_name + ". They found their cohort to be very "+ first_adjetive +" but their teacher was, at least, " +second_adjetive + ". For lunch they have "+first_food+" and " + second_food +" while reviewing their notes. They feel "+feeling+" but are determined to complete the course.")

#print("Hey " + first_name + " " + last_name + "!")